Read Image and Convert the image color

In [7]:
import cv2

In [9]:
img = cv2.imread("C:/Users/Rohit/Desktop/Images/parrot.jpg")

In [10]:
#1 Convert TGB Image to Gray Scale
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [14]:
cv2.imshow('fram1', img)
cv2.imshow('frame2', img_gray)
#press any key with 0 wait time
cv2.waitKey(0)
#close all image frame
cv2.destroyAllWindows()

In [16]:
import cv2

img = cv2.imread("C:/Users/Rohit/Desktop/Images/mp.jpg")

cv2.imshow('Original', img)
# convert BGR format to Grayscale
img_g = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Canny(image, threshold1, threshold2)
# Computing Edge Gradient with canny thresholds
# The edge gradients that are greater tha threshold value will be detected as Edges
# thresholds lower than threshold1 will not be considered as edges.
edges_low = cv2.Canny(img_g, 50, 120)
cv2.imshow('Edge Detection', edges_low)

edges_high = cv2.Canny(img_g, 60, 200)
cv2.imshow('High Edge Detection', edges_high)

# press any key with 0 wait time
cv2.waitKey(0)
# Close all imageframe
cv2.destroyAllWindows()

[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]


In [19]:

import cv2 
import numpy as np

img = cv2.imreadimg = cv2.imread("C:/Users/Rohit/Desktop/Images/pug.jpg")

# Blur using Filter2D
kernel = np.ones((5,5), np.float32) / 25
print(kernel)

# Filter2D
smoothed = cv2.filter2D(img, -1, kernel)

# Average Blur
img_blur = cv2.blur(img, (5,5))

# Median Blur
m_blur = cv2.medianBlur(img, 7)

# Gaussian Blur, sigmaX(stdDev)= 1
g_blur = cv2.GaussianBlur(img, (7,7), 1)


cv2.imshow('Original', img)
cv2.imshow('Blur', smoothed)
cv2.imshow('average', img_blur)
cv2.imshow('median', m_blur)
cv2.imshow('gaussian', g_blur)

# press any key with 0 wait time
cv2.waitKey(0)
# Close all imageframe

[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]


-1