In [1]:
import tensorflow as tf
import keras

C:\Users\Rohit\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
const_1 = tf.constant(100)

In [3]:
const_1.shape

TensorShape([])

In [4]:
const_1.numpy()

100

In [5]:
const_2 = tf.constant([10,20,30,40,50,60,70,80])

In [6]:
const_2.shape

TensorShape([8])

In [7]:
const_2.numpy()

array([10, 20, 30, 40, 50, 60, 70, 80])

In [33]:
const_3 = tf.constant([[10,20,30,40,50,60,70],
                      [10,20,30,40,50,60,70],
                      [10,20,30,40,50,60,70]])

In [34]:
const_3.shape

TensorShape([3, 7])

In [35]:
const_4 = tf.constant([[[10,20,30,40,50,60,70],
                      [10,20,30,40,50,60,70],
                      [10,20,30,40,50,60,70]],

                      [[10,20,30,40,50,60,70],
                      [10,20,30,40,50,60,70],
                      [10,20,30,40,50,60,70]]])

In [36]:
const_4.shape # 3 Dimensions (A tensor)

TensorShape([2, 3, 7])

In [37]:
#This is N-Dimensional representation of a Numpy Array representing various Ranks Line:
#scalar : rank = 0, vector  : rank = 1, matrix : rank = 2, tensor : 3 or more.

In [38]:
X = tf.constant([[8],
                 [9],
                 [11],
                 [7],
                 [10],
                 [12]])

In [39]:
X.shape

TensorShape([6, 1])

In [40]:
W=tf.Variable([[10],
                 [11],
                 [12],
                 [13],
                 [14],
                 [15]])

In [41]:
W.shape

TensorShape([6, 1])

In [42]:
WT = tf.transpose(W)
WT.numpy()

array([[10, 11, 12, 13, 14, 15]])

In [43]:
# Y = WT * X + bias
tf.tensordot(WT,X,axes = 1)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[722]])>

In [44]:
tf.tensordot(X,WT,axes = 1)

<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
array([[ 80,  88,  96, 104, 112, 120],
       [ 90,  99, 108, 117, 126, 135],
       [110, 121, 132, 143, 154, 165],
       [ 70,  77,  84,  91,  98, 105],
       [100, 110, 120, 130, 140, 150],
       [120, 132, 144, 156, 168, 180]])>

Keras:
Keras is high level API based in Tensorflow, to create Deep Learning Neural Networks easily. Dense Neural Network(DNN), CNN & RNN.

In [ ]:
0